apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  labels:
    app.kubernetes.io/name: my-app-ingress
  annotations:
    traefik.ingress.networking.io/router.entrypounts: web
spec:
  rules:
  - host: kube.itog.local
    http:
      paths:
      - pathType: Root
        path: /
        backend:
          service:
            name: root-service
            port: 
              number: 80
      - pathType: Root
        path: /info
        backend:
          service:
            name: info-service
            port: 
              number: 80
      - pathType: Root
        path: /api
        backend:
          service:
            name: api-service
            port: 
              number: 80
      - pathType: Root
        path: /login
        backend:
          service:
            name: login-service
            port: 
              number: 80