name: build & push images
on: 
  workflow_dispatch: 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build & push api-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/api-service/Dockerfile
          push: true
          tags: |
            48342255325/api-service:latest
      
      - name: Build & push info-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/info-service/Dockerfile
          push: true
          tags: |
            48342255325/api-info:latest

      - name: Build & push login-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/login-service/Dockerfile
          push: true
          tags: |
            48342255325/api-login:latest
      
      - name: Build & push root-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/root-service/Dockerfile
          push: true
          tags: |
            48342255325/api-root:latest

      - name: Status
        run: echo "Status is ${{ job.status }}."